### ISSUE TITLE
I can't run `tiled2level` on Debian

### ISSUE THREAD

**Issue by apt1002** [rrthomas/wincoll#24]
![pytmx](https://github.com/user-attachments/assets/531f71cc-82d7-444e-89de-e871a585034c)

`pipx` won't let me install the library `pytmx` because no application depends on it. This means I can't run the `tiled2level` tool.

**Comment by rrthomas** [comment]
This is not a WinColl issue. WinColl depends on pytmx, so you need it installed to run WinColl. `pipx` is for installing applications along with their dependencies, not for libraries.
